[package]
name = "graph"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.0"
bitvec = "1.0.1"
rand = "0.9.0"
slotmap = "1.0.7"
stable-vec = "0.4.1"

[dev-dependencies]
proptest = "1"
